example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from wishlist.views import show_wishlist, tambah_wishlist
from wishlist.views import xml_show_wishlist
from wishlist.views import json_show_wishlist
from wishlist.views import choose_show_wishlist
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import tambah_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', xml_show_wishlist, name='xml_show_wishlist'),
    path('json/', json_show_wishlist, name='json_show_wishlist'),
    path('json/<int:id>', choose_show_wishlist, name='choose_show_wishlist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name = 'show_wishlist_ajax'),
    path('ajax/submit/', tambah_wishlist, name = 'tambah_wishlist'),

]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Trisno Bayu Pamungkas',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    context = {
    'nama': 'Trisno Bayu Pamungkas',
    }
    return render(request, 'wishlist_ajax.html', context)

def tambah_wishlist(request): # Menerima data JSON dan menambahkan BarangWishlist baru ke database
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')

        new_barang = BarangWishlist(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi
        )
        new_barang.save()
        return render(request, 'wishlist_ajax.html')
    return render(request, 'wishlist_ajax.html')
        

def xml_show_wishlist(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def json_show_wishlist(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def choose_show_wishlist(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    
    if id == 1:
        return HttpResponse(serializers.serialize("json", data), content_type="application/json")

    elif id == 2:
        return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # Melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse('wishlist:show_wishlist')) # Membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # Membuat cookie last_login dan dimasukkin ke response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <h1>Hello, world!</h1>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar bg-light">
    <div class="container-fluid">
        <a class="btn btn-secondary" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
        <span class="navbar-text">
            <p>{{nama}}</p>
        </span>
    </div>
</nav>

<table>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% block content %}

<nav class="navbar bg-light">
    <div class="container-fluid">
        <a class="btn btn-secondary" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
        <span class="navbar-text">
            <p>{{nama}}</p>
        </span>
    </div>
</nav>

<form id="submit_wishlist" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>Nama barang: </td>
            <td><input type="text" id="nama_barang" class="form-control"></td>
        </tr>
                
        <tr>
            <td>Harga barang: </td>
            <td><input type="text" id="harga_barang" class="form-control"></td>
        </tr>

        <tr>
            <td>Deskripsi: </td>
            <td><input type="text" id="deskripsi" class="form-control"></td>
        </tr>


        <tr>
            <td></td>
            <td><button type="submit">Tambah Barang</button></td>
        </tr>
    </table>
</form>

<table id = "myTable">
    <thead>    
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<script type="text/javascript">
    $.getJSON("{% url 'wishlist:json_show_wishlist' %}", function(data) {
        console.log("bisaa cuyyy")
        $(data).each(function(key, value) {
            $("#myTable > tbody").append($("<tr>")
                .append($("<td>").append(value.fields.nama_barang))
                .append($("<td>").append(value.fields.harga_barang))
                .append($("<td>").append(value.fields.deskripsi)));
        })
    })

    $(document).on('submit', '#submit_wishlist', function(e) {
        e.preventDefault();
        $.ajax({
            type:"POST",
            url: "{% url 'wishlist:tambah_wishlist' %}",
            dataType: 'json',
            data: {
                nama_barang: $("#nama_barang").val(),
                harga_barang: $("#harga_barang").val(),
                deskripsi: $("#deskripsi").val(),
                csrfmiddlewaretoken:'{{ csrf_token }}',
            },
            success: function(response) {
                console.log("bisaa cuyy")
                alert('Sukses cuy');
                window.location.reload();
            },
        });  
        $("#myTable > tbody").append($("<tr>")
            .append($("<td>").append($("#nama_barang").val()))
            .append($("<td>").append($("#harga_barang").val()))
            .append($("<td>").append($("#deskripsi").val())));
    });
    
</script>

{% endblock content %}